### PR TITLE
Fixes generation of the beta version

### LINKED ISSUE #94: Generate beta version
Hi, @ajsb85

I will add the beta prefix to the version number when the develop branch is updated. 
For example: 1.0.0-beta

Reference:
https://github.com/conventional-changelog/standard-version#release-as-a-pre-release

Best regards.

### PR DESCRIPTION
**Pull request by hectorerb**
Hi, @ajsb85

This PR fix generate beta version.

Close: https://github.com/flyve-mdm/flyve-mdm-ios-agent/issues/94

### CODE REVIEW

**Review by rafaelje — APPROVED** [review]
Reviewed 👍

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Comment by ajsb85** [comment]
And this PR adds support also iOS 9, right?

**Comment by hectorerb** [comment]
Yes, but it is necessary to add support to Inventory library

**Pull request merged**
