### PR TITLE
Create easter egg to show log on agent

### PR DESCRIPTION
**Pull request by hectorerb**
This PR creates easter egg to show log on agent

Closed: https://github.com/flyve-mdm/flyve-mdm-ios-agent/issues/56

### CODE REVIEW

**Review by rafaelje — APPROVED** [review]
It's OK for me 👍

**Review by ajsb85 — APPROVED** [review]
Reviewed.
PD: Try to run the linting tool in every PR.

**Comment by hectorerb** [comment]
@ajsb85 swiftlint?

**Comment by ajsb85** [comment]
@hectorerb Yes, you can run this tool in your IDE.
To clean the code before commit.

**Comment by hectorerb** [comment]
@ajsb85 I'll check it

**Pull request merged**
