### PR TITLE
Create custom HTML for coverage

### PR DESCRIPTION
**Pull request by Gianfranco97**
Hi, @hectorerb 

In this PR I created a way to generate a custom HTML to our needs, this I did with the help of a Ruby gem that I created, here are the links of GitHub and RubyGems:

- https://github.com/Gianfranco97/xcov-report
- https://rubygems.org/gems/fastlane-plugin-xcov_report

Close: https://github.com/flyve-mdm/flyve-mdm-ios-agent/issues/108

### CODE REVIEW

**Review by hectorerb — COMMENTED** [review]
no need to use bundler

**Review by hectorerb — APPROVED** [review]
Fine 👍

**Review by ajsb85 — APPROVED** [review]
Reviewed
Let's run to test

**Comment by ajsb85** [comment]
Hi, @hectorerb 

Your tests failed on CircleCI
Fix it, and restart the build 👍 
To have a green status check before rebase.

Thanks.

**Comment by hectorerb** [comment]
@ajsb85 perfect 👍

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Pull request merged**
